package com.example.flutter_mapquiz

class Translate {
    fun translate(country : String) : String? {
        when(country){
            "Aruba" -> return "Aruba"
            "Afghanistan" -> return "Afganistan"
            "Angola" -> return "Angola"
            "Anguilla" -> return "Anguilla"
            "Albania" -> return "Arnavutluk"
            "Andorra" -> return "Andora"
            "United Arab Emirates" -> return "Birleşik Arap Emirlikleri"
            "Argentina" -> return "Arjantin"
            "Armenia" -> return "Ermenistan"
            "American Samoa" -> return "Amerikan Samoası"
            "Antarctica" -> return "Antarktika"
            "French Southern and Antarctic Lands" -> return "Fransız Güney ve Antarktik Bölgesi"
            "Antigua and Barbuda" -> return "Antigua ve Barbuda"
            "Australia" -> return "Avustralya"
            "Austria" -> return "Avusturya"
            "Azerbaijan" -> return "Azerbaycan"
            "Burundi" -> return "Burundi"
            "Belgium" -> return "Belçika"
            "Benin" -> return "Benin"
            "Burkina Faso" -> return "Burkina Faso"
            "Bangladesh" -> return "Bangladeş"
            "Bulgaria" -> return "Bulgaristan"
            "Bahrain" -> return "Bahreyn"
            "The Bahamas" -> return "Bahamalar"
            "Bosnia and Herzegovina" -> return "Bosna Hersek"
            "Saint Barthelemy" -> return "Saint Barthelemy"
            "Belarus" -> return "Belarus"
            "Belize" -> return "Belize"
            "Bermuda" -> return "Bermuda Adaları"
            "Bolivia" -> return "Bolivya"
            "Brazil" -> return "Brezilya"
            "Barbados" -> return "Barbados"
            "Brunei" -> return "Brunei"
            "Bhutan" -> return "Butan Krallığı"
            "Botswana" -> return "Botsvana"
            "Central African Republic" -> return "Orta Afrika Cumhuriyeti"
            "Canada" -> return "Kanada"
            "Switzerland" -> return "İsviçre"
            "Chile" -> return "Şili"
            "China" -> return "Çin"
            "Ivory Coast" -> return "Fildişi Sahili"
            "Cameroon" -> return "Kamerun"
            "Democratic Republic of the Congo" -> return "Kongo Demokratik Cumhuriyeti"
            "Republic of the Congo" -> return "Kongo Cumhuriyeti"
            "Cook Islands" -> return "Cook Adaları"
            "Colombia" -> return "Kolombiya"
            "Comoros" -> return "Komor Adaları"
            "Cape Verde" -> return "Cabo Verde(Yeşil Burun Adaları)"
            "Costa Rica" -> return "Kosta Rika"
            "Cuba" -> return "Küba"
            "Curaao" -> return "Curaçao"
            "Cayman Islands" -> return "Cayman Adaları"
            "Cyprus" -> return "Kıbrıs"
            "Czech Republic" -> return "Çek Cumhuriyeti"
            "Germany" -> return "Almanya"
            "Djibouti" -> return "Cibuti"
            "Dominica" -> return "Dominika"
            "Denmark" -> return "Danimarka"
            "Dominican Republic" -> return "Dominik Cumhuriyeti"
            "Algeria" -> return "Cezayir"
            "Ecuador" -> return "Ekvador"
            "Egypt" -> return "Mısır"
            "Eritrea" -> return "Eritre"
            "Spain" -> return "İspanya"
            "Estonia" -> return "Estonya"
            "Ethiopia" -> return "Etiyopya"
            "Finland" -> return "Finlandiya"
            "Fiji" -> return "Fiji"
            "Falkland Islands" -> return "Falkland Adaları"
            "France" -> return "Fransa"
            "Faroe Islands" -> return "Faroe Adaları"
            "Federated States of Micronesia" -> return "Mikronezya"
            "Gabon" -> return "Gabon"
            "United Kingdom" -> return "Birleşik Krallık"
            "Georgia" -> return "Gürcistan"
            "Guernsey" -> return "Guernsey"
            "Ghana" -> return "Gana"
            "Guinea" -> return "Gine"
            "Gambia" -> return "Gambiya"
            "Guinea Bissau" -> return "Gine Bissau"
            "Equatorial Guinea" -> return "Ekvator Ginesi"
            "Greece" -> return "Yunanistan"
            "Grenada" -> return "Grenada"
            "Greenland" -> return "Grönland"
            "Guatemala" -> return "Guatemala"
            "Guam" -> return "Guam"
            "Guyana" -> return "Guyana"
            "Hong Kong S.A.R." -> return "Hong Kong"
            "Heard Island and McDonald Islands" -> return "Heard Adası ve McDonald Adaları"
            "Honduras" -> return "Honduras"
            "Croatia" -> return "Hırvatistan"
            "Haiti" -> return "Haiti"
            "Hungary" -> return "Macaristan"
            "Indonesia" -> return "Endonezya"
            "Isle of Man" -> return "Man Adası"
            "India" -> return "Hindistan"
            "British Indian Ocean Territory" -> return "Britanya Hint Okyanusu Toprakları"
            "Ireland" -> return "İrlanda"
            "Iran" -> return "İran"
            "Iraq" -> return "Irak"
            "Iceland" -> return "İzlanda"
            "Israel" -> return "Filistin"
            "Italy" -> return "İtalya"
            "Jamaica" -> return "Jamaika"
            "Jersey" -> return "Jersey"
            "Jordan" -> return "Ürdün"
            "Japan" -> return "Japonya"
            "Kazakhstan" -> return "Kazakistan"
            "Kenya" -> return "Kenya"
            "Kyrgyzstan" -> return "Kırgızistan"
            "Cambodia" -> return "Kamboçya"
            "Kiribati" -> return "Kiribati"
            "Saint Kitts and Nevis" -> return "Saint Kitts ve Nevis"
            "South Korea" -> return "Güney Kore"
            "Kuwait" -> return "Kuveyt"
            "Laos" -> return "Laos"
            "Lebanon" -> return "Lübnan"
            "Liberia" -> return "Liberya"
            "Libya" -> return "Libya"
            "Saint Lucia" -> return "Saint Lucia"
            "Liechtenstein" -> return "Lihtenştayn"
            "Sri Lanka" -> return "Sri Lanka"
            "Lesotho" -> return "Lesotho"
            "Lithuania" -> return "Litvanya"
            "Luxembourg" -> return "Lüksemburg"
            "Latvia" -> return "Letonya"
            "Macau S.A.R" -> return "Makao"
            "Saint Martin" -> return "Saint Martin"
            "Morocco" -> return "Fas"
            "Monaco" -> return "Monako"
            "Moldova" -> return "Moldova"
            "Madagascar" -> return "Madagaskar"
            "Maldives" -> return "Maldivler"
            "Mexico" -> return "Meksika"
            "Marshall Islands" -> return "Marshall Adaları"
            "Macedonia" -> return "Makedonya"
            "Mali" -> return "Mali"
            "Malta" -> return "Malta"
            "Myanmar" -> return "Myanmar"
            "Montenegro" -> return "Karadağ"
            "Mongolia" -> return "Moğolistan"
            "Northern Mariana Islands" -> return "Kuzey Mariana Adaları"
            "Mozambique" -> return "Mozambik"
            "Mauritania" -> return "Moritanya"
            "Montserrat" -> return "Montserrat"
            "Mauritius" -> return "Mauritius"
            "Malawi" -> return "Malavi"
            "Malaysia" -> return "Malezya"
            "Namibia" -> return "Namibya"
            "New Caledonia" -> return "Yeni Kaledonya"
            "Niger" -> return "Nijer"
            "Norfolk Island" -> return "Norfolk Adası"
            "Nigeria" -> return "Nijerya"
            "Nicaragua" -> return "Nikaragua"
            "Niue" -> return "Niue"
            "Netherlands" -> return "Hollanda"
            "Norway" -> return "Norveç"
            "Nepal" -> return "Nepal"
            "Nauru" -> return "Nauru"
            "New Zealand" -> return "Yeni Zelanda"
            "Oman" -> return "Umman"
            "Pakistan" -> return "Pakistan"
            "Panama" -> return "Panama"
            "Pitcairn Islands" -> return "Pitcairn Adaları"
            "Peru" -> return "Peru"
            "Philippines" -> return "Filipinler"
            "Palau" -> return "Palau"
            "Papua New Guinea" -> return "Yeni Gine"
            "Poland" -> return "Polonya"
            "Puerto Rico" -> return "Porto Riko"
            "North Korea" -> return "Kuzey Kore"
            "Portugal" -> return "Portekiz"
            "Paraguay" -> return "Paraguay"
            "French Polynesia" -> return "Fransız Polinezyası"
            "Qatar" -> return "Katar"
            "Romania" -> return "Romanya"
            "Russia" -> return "Rusya"
            "Rwanda" -> return "Ruanda"
            "Saudi Arabia" -> return "Suudi Arabistan"
            "Sudan" -> return "Sudan"
            "Senegal" -> return "Senegal"
            "Singapore" -> return "Singapur"
            "South Georgia and the Islands" -> return "Güney Georgia ve Adaları"
            "Saint Helena" -> return "Saint Helena"
            "Solomon Islands" -> return "Solomon Adaları"
            "Sierra Leone" -> return "Sierra Leone"
            "El Salvador" -> return "El Salvador"
            "San Marino" -> return "San Marino"
            "Somalia" -> return "Somali"
            "Saint Pierre and Miquelon" -> return "Saint Pierre ve Miquelon"
            "Republic of Serbia" -> return "Sırbistan"
            "Sao Tome and Principe" -> return "Sao Tome ve Principe"
            "Suriname" -> return "Surinam"
            "Slovakia" -> return "Slovakya"
            "Slovenia" -> return "Slovenya"
            "Sweden" -> return "İsveç"
            "Swaziland" -> return "Svaziland(Esvati̇ni̇)"
            "Sint Maarten" -> return "Sint Maarten"
            "Seychelles" -> return "Seyşeller"
            "Syria" -> return "Suriye"
            "Turks and Caicos Islands" -> return "Turks ve Caicos Adaları"
            "Chad" -> return "Çad"
            "Togo" -> return "Togo"
            "Thailand" -> return "Tayland"
            "Tajikistan" -> return "Tacikistan"
            "Turkmenistan" -> return "Türkmenistan"
            "East Timor" -> return "Doğu Timor"
            "Tonga" -> return "Tonga"
            "Trinidad and Tobago" -> return "Trinidad ve Tobago"
            "Tunisia" -> return "Tunus"
            "Turkey" -> return "Türkiye"
            "Taiwan" -> return "Tayvan"
            "United Republic of Tanzania" -> return "Tanzanya"
            "Uganda" -> return "Uganda"
            "Ukraine" -> return "Ukrayna"
            "Uruguay" -> return "Uruguay"
            "United States" -> return "ABD"
            "Uzbekistan" -> return "Özbekistan"
            "Vatican" -> return "Vatikan"
            "Saint Vincent and the Grenadines" -> return "Saint Vincent ve Grenadinler"
            "Venezuela" -> return "Venezuela"
            "British Virgin Islands" -> return "Britanya Virjin Adaları"
            "United States Virgin Islands" -> return "ABD Virjin Adaları"
            "Vietnam" -> return "Vietnam"
            "Vanuatu" -> return "Vanuatu"
            "Wallis and Futuna" -> return "Wallis ve Futuna"
            "Samoa" -> return "Samoa"
            "Yemen" -> return "Yemen"
            "South Africa" -> return "Güney Afrika"
            "Zambia" -> return "Zambiya"
            "Zimbabwe" -> return "Zimbabve"
        }
        return null
    }
}