class Country {
  List<String> countries = <String>[
    'ABD',
    'ABD Virjin Adaları',
    'Afganistan',
    'Almanya',
    'Amerikan Samoası',
    'Andora',
    'Angola',
    'Antigua ve Barbuda',
    'Arjantin',
    'Arnavutluk',
    'Aruba',
    'Avustralya',
    'Azerbaycan',
    'Bahamalar',
    'Bahreyn',
    'Bangladeş',
    'Barbados',
    'Belarus',
    'Belize',
    'Belçika',
    'Benin',
    'Bermuda Adaları',
    'Birleşik Arap Emirlikleri',
    'Birleşik Krallık',
    'Bolivya',
    'Bosna Hersek',
    'Botsvana',
    'Brezilya',
    'Britanya Hint Okyanusu Toprakları',
    'Britanya Virjin Adaları',
    'Brunei',
    'Bulgaristan',
    'Burkina Faso',
    'Burundi',
    'Butan Krallığı',
    'Cabo Verde(Yeşil Burun Adaları)',
    'Cayman Adaları',
    'Cezayir',
    'Cezayir',
    'Cook Adaları',
    'Curaçao',
    'Çad',
    'Çek Cumhuriyeti',
    'Çin',
    'Danimarka',
    'Dominik Cumhuriyeti',
    'Dominika',
    'Doğu Timor',
    'Ekvador',
    'Ekvator Ginesi',
    'El Salvador',
    'Endonezya',
    'Eritre',
    'Ermenistan',
    'Estonya',
    'Etiyopya',
    'Falkland Adaları',
    'Faroe Adaları',
    'Fas',
    'Fiji',
    'Fildişi Sahili',
    'Filipinler',
    'Finlandiya',
    'Fransa',
    'Fransız Güney ve Antarktik Bölgesi',
    'Fransız Polinezyası',
    'Gabon',
    'Gambiya',
    'Gana',
    'Gine',
    'Gine Bissau',
    'Grenada',
    'Grönland',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guyana',
    'Güney Afrika',
    'Güney Georgia ve Adaları',
    'Güney Kore',
    'Gürcistan',
    'Haiti',
    'Heard Adası ve McDonald Adaları',
    'Hindistan',
    'Hollanda',
    'Honduras',
    'Hong Kong',
    'Hırvatistan',
    'Irak',
    'İran',
    'İrlanda',
    'İspanya',
    'İsrail',
    'İsveç',
    'İsviçre',
    'İtalya',
    'İzlanda',
    'Jamaika',
    'Japonya',
    'Jersey',
    'Kamboçya',
    'Kamerun',
    'Kanada',
    'Kanada',
    'Katar',
    'Kazakistan',
    'Kenya',
    'Kiribati',
    'Kolombiya',
    'Komor Adaları',
    'Kongo Cumhuriyeti',
    'Kongo Demokratik Cumhuriyeti',
    'Kosta Rika',
    'Kuveyt',
    'Kuzey Kore',
    'Kuzey Mariana Adaları',
    'Küba',
    'Kıbrıs',
    'Kırgızistan',
    'Laos',
    'Lesotho',
    'Letonya',
    'Liberya',
    'Libya',
    'Lihtenştayn',
    'Litvanya',
    'Lübnan',
    'Lüksemburg',
    'Macaristan',
    'Madagaskar',
    'Makao',
    'Makedonya',
    'Malavi',
    'Maldivler',
    'Malezya',
    'Mali',
    'Malta',
    'Man Adası',
    'Marshall Adaları',
    'Mauritius',
    'Meksika',
    'Mikronezya',
    'Moldova',
    'Monako',
    'Montserrat',
    'Montserrat',
    'Mozambik',
    'Moğolistan',
    'Myanmar',
    'Mısır',
    'Namibya',
    'Namibya',
    'Nepal',
    'Nijer',
    'Nijerya',
    'Nikaragua',
    'Niue',
    'Norfolk Adası',
    'Norveç',
    'Orta Afrika Cumhuriyeti',
    'Özbekistan',
    'Pakistan',
    'Palau',
    'Panama',
    'Paraguay',
    'Peru',
    'Pitcairn Adaları',
    'Polonya',
    'Portekiz',
    'Porto Riko',
    'Romanya',
    'Ruanda',
    'Rusya',
    'Saint Barthelemy',
    'Saint Helena',
    'Saint Kitts ve Nevis',
    'Saint Lucia',
    'Saint Martin',
    'Saint Pierre ve Miquelon',
    'Saint Vincent ve Grenadinler',
    'Samoa',
    'San Marino',
    'Sao Tome ve Principe',
    'Senegal',
    'Seyşeller',
    'Sierra Leone',
    'Singapur',
    'Sint Maarten',
    'Slovakya',
    'Slovenya',
    'Solomon Adaları',
    'Somali',
    'Sri Lanka',
    'Sudan',
    'Surinam',
    'Suriye',
    'Suudi Arabistan',
    'Svaziland(Esvati̇ni̇)',
    'Sırbistan',
    'Şili',
    'Tacikistan',
    'Tanzanya',
    'Tayland',
    'Tayvan',
    'Togo',
    'Tonga',
    'Trinidad ve Tobago',
    'Tunus',
    'Turks ve Caicos Adaları',
    'Türkiye',
    'Türkmenistan',
    'Uganda',
    'Ukrayna',
    'Umman',
    'Uruguay',
    'Ürdün',
    'Vanuatu',
    'Vatikan',
    'Venezuela',
    'Vietnam',
    'Wallis ve Futuna',
    'Yemen',
    'Yeni Gine',
    'Yeni Kaledonya',
    'Yeni Zelanda',
    'Yunanistan',
    'Zambiya',
    'Zimbabve'
  ];

  List<String> getCountries() {
    return countries;
  }
}
